layout: stacked
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  dribbble: sagaya_hafeez
  # facebook: your_username
  linkedin: sagayaabdulhafeez
  medium: ___shaggy_
  # stackoverflow: your_user_id
  twitter: sagaya_hafeez
  # youtube: your_username

topics:
  - name: iOS
    web_url: https://github.com/topics/swift
    image_url: https://www.macincloud.com/pages/images/xcode-icon.png

  - name: Kotlin
    web_url: https://github.com/topics/kotlin
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Kotlin-logo.svg/220px-Kotlin-logo.svg.png

  - name: Swift
    web_url: https://github.com/topics/swift
    image_url: https://cdn4.iconfinder.com/data/icons/logos-3/504/Swift-2-512.png
    
  - name: Flask
    web_url: https://github.com/topics/flask
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Flask_logo.svg/1200px-Flask_logo.svg.png
    
    
